openapi: 3.0.1
info:
  title: PHP Challenge 20230105
  description: API Products
  version: '0.1'
servers:
  - url: http://localhost
    description: Local
paths:
  /products/{code}:
    delete:
      summary: Change status of product to trash on database
      description: Delete product by code
      operationId: deleteProduct
      parameters:
        - in: path
          name: code
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: Product deleted
        '404':
          description: Product not found
    get:
      summary: Get information of only a product from database
      description: Get product by code
      operationId: getProduct
      parameters:
        - in: path
          name: code
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: A product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
  /products:
    get:
      summary: List all products in database with pagination
      description: Returns all products from the store
      operationId: listProducts
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          required: false
        - in: query
          name: page
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: A array of products
          content:
            application/json:
              schema:
                type: array
components:
  schemas:
    Product:
      type: object
      properties:
        code:
          type: integer
        status:
          type: string
        imported_t:
          type: string
        url:
          type: string
        creator:
          type: string
        created_t:
          type: integer
        last_modified_t:
          type: integer
        product_name:
          type: string
        quantity:
          type: string
        brands:
          type: string
        categories:
          type: string
        labels:
          type: string
        cities:
          type: string
        purchase_places:
          type: string
        stores:
          type: string
        ingredients_text:
          type: string
        traces:
          type: string
        serving_size:
          type: string
        serving_quantity:
          type: number
        nutriscore_score:
          type: integer
        nutriscore_grade:
          type: string
        main_category:
          type: string
        image_url:
          type: string
